In [1]:
import pandas as pd
A = pd.read_csv("C:/Users/Audi/Downloads/Google_Stock_Price_Train.csv")

In [2]:
A.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

# Missing data treatement

In [3]:
A.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

# Get stock opening price¶ and for Neural Network we need to give the data in Array

TO convert the DF to Array we can use two method 
1. .Values 2. np.array

In [4]:
trd = A[["Open"]].values

In [5]:
trd

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [6]:
import numpy as np
np.array(A[["Open"]])

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

# Once we cconvert the data we need to scale the data using MinmaxScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit_transform(trd)

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# So data is is in standerd format do need to Create Data for training and testing

In [8]:
trd.shape

(1258, 1)

Will create training data in 2 list--- xtrain & ytrain

In [9]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])  

In [10]:
xtrain

[array([[325.25],
        [331.27],
        [329.83],
        [328.34],
        [322.04],
        [313.7 ],
        [310.59],
        [314.43],
        [311.96],
        [314.81],
        [312.14],
        [319.3 ],
        [294.16],
        [291.91],
        [292.07],
        [287.68],
        [284.92],
        [284.32],
        [287.95],
        [290.41],
        [291.38],
        [291.34],
        [294.23],
        [296.39],
        [302.44],
        [303.18],
        [304.87],
        [302.81],
        [304.11],
        [304.63],
        [305.32],
        [300.28],
        [301.36],
        [300.81],
        [304.84],
        [302.37],
        [302.54],
        [302.16],
        [303.86],
        [308.14],
        [309.97],
        [309.84],
        [309.06],
        [302.89],
        [303.39],
        [303.88],
        [302.84],
        [298.88],
        [303.24],
        [306.35]]),
 array([[331.27],
        [329.83],
        [328.34],
        [322.04],
        [313.7 ],
        

In [11]:
ytrain

[array([[307.15]]),
 array([[309.29]]),
 array([[310.4]]),
 array([[314.28]]),
 array([[316.12]]),
 array([[318.06]]),
 array([[322.09]]),
 array([[321.3]]),
 array([[322.31]]),
 array([[324.8]]),
 array([[325.5]]),
 array([[324.66]]),
 array([[319.19]]),
 array([[321.5]]),
 array([[318.03]]),
 array([[314.94]]),
 array([[313.07]]),
 array([[315.58]]),
 array([[315.8]]),
 array([[319.98]]),
 array([[322.57]]),
 array([[310.34]]),
 array([[303.14]]),
 array([[302.89]]),
 array([[301.71]]),
 array([[301.]]),
 array([[295.34]]),
 array([[298.]]),
 array([[300.87]]),
 array([[304.31]]),
 array([[306.36]]),
 array([[305.35]]),
 array([[300.77]]),
 array([[299.48]]),
 array([[303.67]]),
 array([[301.83]]),
 array([[296.39]]),
 array([[301.63]]),
 array([[302.28]]),
 array([[305.34]]),
 array([[304.04]]),
 array([[299.27]]),
 array([[301.54]]),
 array([[307.83]]),
 array([[315.73]]),
 array([[311.38]]),
 array([[299.13]]),
 array([[305.57]]),
 array([[299.7]]),
 array([[303.44]]),
 array([[29

print(xtrain[1],"\n") print(ytrain[1])

In [12]:
type(xtrain)

list

In [13]:
xtr = np.array(xtrain)

In [14]:
xtr.shape


(1208, 50, 1)

In [15]:
ytr = np.array(ytrain)

In [16]:
ytr.shape

(1208, 1, 1)

# Create a NN

In [17]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout

In [18]:
#pip install numpy==1.19.5

In [19]:
nn = Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dense(1))

In [20]:
nn.compile(optimizer="adam",loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=100)

Epoch 1/100
38/38 [==============================] - 3s 84ms/step - loss: 310037.1875
Epoch 2/100
38/38 [==============================] - 3s 79ms/step - loss: 300645.0000
Epoch 3/100
38/38 [==============================] - 3s 75ms/step - loss: 295618.4375
Epoch 4/100
38/38 [==============================] - 3s 77ms/step - loss: 291200.4375
Epoch 5/100
38/38 [==============================] - 3s 71ms/step - loss: 286989.3438
Epoch 6/100
38/38 [==============================] - 3s 69ms/step - loss: 282909.2812
Epoch 7/100
38/38 [==============================] - 3s 74ms/step - loss: 278910.4688
Epoch 8/100
38/38 [==============================] - 3s 76ms/step - loss: 275008.6250
Epoch 9/100
38/38 [==============================] - 3s 75ms/step - loss: 271165.4062
Epoch 10/100
38/38 [==============================] - 3s 76ms/step - loss: 267386.3438
Epoch 11/100
38/38 [==============================] - 3s 66ms/step - loss: 263666.8750
Epoch 12/100
38/38 [==============================] 