# Read the Data

In [1]:
import pandas as pd
A = pd.read_csv("C:/Users/Audi/Downloads/Google_Stock_Price_Train.csv")

In [2]:
A.head(7)

Date    Open    High     Low   Close      Volume
0   1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1   1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2   1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3   1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4   1/9/2012  322.04  322.29  309.46  620.76  11,688,800
5  1/10/2012  313.70  315.72  307.30  621.43   8,824,000
6  1/11/2012  310.59  313.52  309.40  624.25   4,817,800

# Missing Data

In [3]:
A.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

# Get stock opening price

In [4]:
trd = A[["Open"]].values

In [5]:
import numpy as np
np.array(A[["Open"]])

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

# MinmaxScaler

In [6]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit_transform(trd)


array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create Data for training and testing

In [7]:
trd.shape

(1258, 1)

In [8]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])  

In [9]:
type(xtrain)

list

# Conver data in Array

In [10]:
xtr = np.array(xtrain)

In [11]:
xtr.shape

(1208, 50, 1)

In [12]:
ytr = np.array(ytrain)

In [13]:
ytr.shape

(1208, 1, 1)

# Create a NN Model

In [14]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout

In [15]:
nn = Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dense(1))

In [16]:
nn.compile(optimizer="adam",loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=10)

Epoch 1/10
38/38 [==============================] - 3s 88ms/step - loss: 308762.9375
Epoch 2/10
38/38 [==============================] - 3s 76ms/step - loss: 298461.5938 0s - loss: 298461.59
Epoch 3/10
38/38 [==============================] - 3s 67ms/step - loss: 293458.8438
Epoch 4/10
38/38 [==============================] - 3s 67ms/step - loss: 289026.6250
Epoch 5/10
38/38 [==============================] - 2s 66ms/step - loss: 284800.4375
Epoch 6/10
38/38 [==============================] - 3s 68ms/step - loss: 280700.0625
Epoch 7/10
38/38 [==============================] - 3s 67ms/step - loss: 276706.2812
Epoch 8/10
38/38 [==============================] - 3s 72ms/step - loss: 272696.7812
Epoch 9/10
38/38 [==============================] - 3s 71ms/step - loss: 268764.6250
Epoch 10/10
38/38 [==============================] - 3s 70ms/step - loss: 264919.3438


# Read data of test file

In [4]:
tsd = pd.read_csv("C:/Users/Audi/Downloads/Google_Stock_Price_Test.csv")

In [5]:
tsd.head()

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2  1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3  1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4  1/9/2017  806.40  809.97  802.83  806.65  1,272,400

# Preprocessing for test data same as training data

In [28]:
tsd.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [29]:
tsd

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

In [30]:
tsd[["Open"]]

Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [31]:
tsd.shape

(20, 6)

In [32]:
trd.shape

(1258, 1)

In [34]:
Q = pd.concat([A,tsd])
Q.index = range(0,1278)

In [35]:
Q = Q[["Open"]].values

In [36]:
xtest = []
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [37]:
xts = np.array(xtest)

In [38]:
xts.shape

(19, 50, 1)

In [39]:
tsd


Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

In [40]:
nn.predict(xts)

array([[[37.122574],
        [50.313824],
        [52.123917],
        [52.37597 ],
        [52.410885],
        [52.41575 ],
        [52.41643 ],
        [52.416527],
        [52.416542],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.41654 ],
        [52.4